spring:
  redis:
    #数据库索引
    database: 0
    host: 127.0.0.1
    port: 6379
    password: password
    #连接超时时间
    timeout: 5000
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      routes:
        # 认证中心的路由
        - id: mall-auth
          uri: lb://mall-auth
          predicates:
            - Path=/mall-auth/**
          filters:
            - StripPrefix=1
