server:
  port: 20200

spring:
  application:
    name: mall-admin
  profiles:
    active: '@spring.active@'
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        watch-delay: 1000

