server:
  port: 22333

spring:
  application:
    name: mall-id-generator
  profiles:
    active: '@spring.active@'
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        watch-delay: 1000
